### ISSUE TITLE
hydra::fill_random fails to compile with declared arguments

### ISSUE THREAD

**Issue by adicanto** [MultithreadCorner/Hydra#105]
The following code doesn't compile because "The container is not iterable, or it is not convertible from/to the functor return value". Changing ``X`` with ``double`` in the container definition fixes the compilation, which hints to an issue with the conversion/understanding of the declared argument.
```
declarg(X, double)
using namespace hydra::arguments;
...
hydra::device::vector<X> data(n);
hydra::fill_random(data, hydra::UniformShape<X>(0.,1.) );
...
```

**Comment by dbrundu** [comment]
I'm observing the same error. In addition, putting the container in the `host` and using `X` type, fixes the compilation, so could be related to device reference conversions.

**Comment by AAAlvesJr** [comment]
Thanks for the opening the issue. @dbrundu what `host` and `device` mean in your case? are you running in gpu?

**Comment by dbrundu** [comment]
No, I'm running in CPU. For example with `TBB` using the `host` vector compiles while `device` vector not.

**Comment by AAAlvesJr** [comment]
Ok, I reproduce the bug. Starting to investigate...

**Comment by AAAlvesJr** [comment]
just pushed  fix, all works on my box. let me know if you still have issues.

**Comment by adicanto** [comment]
It works now

**Comment by AAAlvesJr** [comment]
Perfect, thanks. Closing now...
