### ISSUE TITLE
Hydra on Nvidia A100

### ISSUE THREAD

**Issue by acontu** [MultithreadCorner/Hydra#108]
Cannot compile examples due to unsupported GPU architecture. The A100 should be number 80

**Comment by AAAlvesJr** [comment]
Thanks for opening this issue. 
Just submitted a potential solution. Please, test the master branch and let us know if it worked.

**Comment by acontu** [comment]
I tested your solution and it fixes the issue. Thank you.

**Comment by AAAlvesJr** [comment]
good. thanks,
