### ISSUE TITLE
Capitalization in hydra dev

### ISSUE THREAD

**Issue by henryiii** [MultithreadCorner/Hydra#11]
Some of the files that used to work in Hydra 1 are broken in Hydra dev fork because they are referred to (for example, in `hydra/Events.h`) with differing capitalization (`#include <hydra/detail/config.h>`, but the file is `Config.h`.

Personally recommend identical caps for all files, either TitleCase or lowercase. Thrust uses lowercase.

**Comment by AAAlvesJr** [comment]
config.h is not compliant with coding rules.

**Comment by AAAlvesJr** [comment]
Config.h will be kept in the incoming release.

**Comment by henryiii** [comment]
That's fine, but the include statements need to be changed to `...Config.h>`.

**Comment by AAAlvesJr** [comment]
it is the case in the incoming relase... dont worry,
