### ISSUE TITLE
Misprint in example simultaneous_fit.inl

### ISSUE THREAD

**Issue by Hiigaran** [MultithreadCorner/Hydra#111]
Hi,

In the example "simultaneous_fit.inl" in lines 142 and 151, I think there is zsigma instead of xsigma and ysigma, respectively.

Kind regards

Alessandro

**Comment by AAAlvesJr** [comment]
Thank you for your report. A solution has been committed, please test and let us know if it works fine now. So we can close this issue.

**Comment by Hiigaran** [comment]
Hi,

I compiled the examples. Now I obtain the error message "error while
loading shared libraries: libMatrix.so.6.22: cannot open shared object
file: No such file or directory" when I try to launch each example.

Alessandro

Il giorno dom 25 apr 2021 alle ore 18:03 Antonio Augusto Alves Junior <
***@***.***> ha scritto:

**Comment by Hiigaran** [comment]
Hi,

I investigated the problem. My system does not see a ROOT library,
that instead exists. So, I think the problem is on my side and you can
close the issue.

Kind regards

Alessandro

Il giorno lun 26 apr 2021 alle ore 16:50 Alessandro Maria Ricci <
***@***.***> ha scritto:

**Comment by Hiigaran** [comment]
Hi,

I confirm that the problem was on my side. You can close the issue. Thank you.

**Comment by AAAlvesJr** [comment]
ok. thanks closing.
