### ISSUE TITLE
Inline missing

### ISSUE THREAD

**Issue by henryiii** [MultithreadCorner/Hydra#12]
Hyrda has inherited an issue from MCBooster; at least one non-templated function (`operator<<` for `hydra::Parameter`) is not marked `inline`. If you try to use Hydra in two different files and link them, the `operator<<` kills the linking with multiple definition errors.

`hydra::PrintLevel` also.

**Comment by AAAlvesJr** [comment]
Inline will not help here since is the compiler who decides in last instance.  Provide more details about this issue in order i can reproduce that.

**Comment by henryiii** [comment]
Inline is needed for any non-tempate function in a header only library. 

To reproduce, simply make two separate files that `#include` a hydra non-inlined function (they don’t have to use it). Compile separately and link. Immediate symbol name clash error.

Inline does not force the compiler to inline, but it is required for any header only library. See https://en.wikipedia.org/wiki/Header-only <https://en.wikipedia.org/wiki/Header-only> or https://news.ycombinator.com/item?id=8003200 <https://news.ycombinator.com/item?id=8003200>

**Comment by AAAlvesJr** [comment]
Confirmed... to be implemented in the incoming release.
