### ISSUE TITLE
Eigen copy does not support CUDA 9

### ISSUE THREAD

**Issue by henryiii** [MultithreadCorner/Hydra#15]
The copy of Eigen that's baked into AAAlvesJr/Hydra does not work with CUDA 9. It uses the now removed `__CUDACC_VER__`. The fix has been applied to both master and 3.3 branches of Eigen.

**Comment by henryiii** [comment]
If you want the commit hash of the fix (3.3 version of fix): https://bitbucket.org/eigen/eigen/commits/a201b8438d36a3cec3db71b870b11f9304effe2f?at=3.3

**Comment by henryiii** [comment]
There's another error with Half, and that's not yet fixed in master (and the half-way fix wasn't ported back to 3.3). So Eigen doesn't support CUDA 9 yet at all. I'm going to try to get access to the Eigen bug tracker.

**Comment by AAAlvesJr** [comment]
Solved!
