### ISSUE TITLE
Issues with ROOT missing

### ISSUE THREAD

**Issue by henryiii** [MultithreadCorner/Hydra#22]
Hydra can't quite build if ROOT is missing. So far, unprotected includes in `basic_fit` and `splot` are causing errors. These examples could be ignored if ROOT is not found, or protection could be added around the ROOT parts.

- [ ] `basic_fit`
- [ ] `splot`

Fixes are needed in both Develop and 2.0rc branches (cherry-pick fixes).

```
In file included from /Users/henryiii/git/fitting/Hydra/hydra/FCN.h:41:0,
                 from /Users/henryiii/git/fitting/Hydra/hydra/LogLikelihoodFCN.h:32,
                 from /Users/henryiii/git/fitting/Hydra/examples/fit/basic_fit.inl:46,
                 from /Users/henryiii/git/fitting/Hydra/examples/fit/basic_fit.cpp:31:
/Users/henryiii/git/fitting/Hydra/hydra/UserParameters.h:43:10: fatal error: Minuit2/MnUserParameterState.h: No such file or directory
 #include "Minuit2/MnUserParameterState.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [examples/fit/CMakeFiles/basic_fit_tbb.dir/basic_fit.cpp.o] Error 1
make[1]: *** [examples/fit/CMakeFiles/basic_fit_tbb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /Users/henryiii/git/fitting/Hydra/hydra/FCN.h:41:0,
                 from /Users/henryiii/git/fitting/Hydra/hydra/LogLikelihoodFCN.h:32,
                 from /Users/henryiii/git/fitting/Hydra/examples/fit/splot.inl:48,
                 from /Users/henryiii/git/fitting/Hydra/examples/fit/splot.cpp:30:
/Users/henryiii/git/fitting/Hydra/hydra/UserParameters.h:43:10: fatal error: Minuit2/MnUserParameterState.h: No such file or directory
 #include "Minuit2/MnUserParameterState.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [examples/fit/CMakeFiles/splot_omp.dir/splot.cpp.o] Error 1
make[1]: *** [examples/fit/CMakeFiles/splot_omp.dir/all] Error 2
```

**Comment by henryiii** [comment]
Note: if it's just Minuit2 for the fitting, the Minuit2 package I have could be used to add Minuit automatically to the build. Let me know if you are interested in that, I can add it with a `file(DOWNLOAD ...` in the CMake file.

**Comment by AAAlvesJr** [comment]
I will place guards in the corresponding examples. Fit related  stuff should be included only when minuit2 is available. 
A.A.

**Comment by eduardo-rodrigues** [comment]
If I may add a suggestion here, for beyond release 2.0.0: personally I would take out all examples from the header-only package. This would make things cleaner. Then by construction the dependencies for Hydra are smaller and anyone wanting to prepare the examples (from the new package) would know that it may require ROOT, etc. Maybe worth having a thought ...

**Comment by AAAlvesJr** [comment]
Can you elaborate this a bit more Eduardo? 
All Hydra headers are on ```Hydra/hydra```. This is what the user will include in his source tree. Examples are on ```Hydra/examples``` folder. It seems quite separated too me.

**Comment by eduardo-rodrigues** [comment]
I mean that once I get Hydra and want to start by getting a feeling for it via the examples, which seems the best starting point, I will immediately need to compile and have a ROOT installation compatible with the relevant compiler. That adds a dependency that could be made separate from Hydra itself, which is totally independent from ROOT. It's merely a comment about packaging and distribution.

**Comment by AAAlvesJr** [comment]
Are you talking about Minuit2, right ?
ROOT is necessary only to deploy the interface to Minuit2 in Hydra. So I deduce you are talking about Minuit2...

As you can see here:
https://seal.web.cern.ch/seal/snapshot/work-packages/mathlibs/minuit/
The last release of a standalone package for Minuit2 corresponds to ROOT 5.34.14.
So, before to use standalone  Minuit2 installation, would be necessary to understand if (and what ) changed  since then.

**Comment by eduardo-rodrigues** [comment]
Yes. So you are taking a standalone version of Minuit2 and not the one from more modern ROOT releases? Anyway you get my point, which is a general comment.
Note that SEAL has been dropped many years ago as far as I know.

**Comment by henryiii** [comment]
I'm currently discussing with the ROOT team to try to get my CMake based Minuit2 build merged with ROOT. Once that's done, it will be trivial to have Hydra add Minuit2 if it's missing (that's exactly what GooFit does and why I developed the Minuit2 CMake standalone).

It's here, feel free to test: https://github.com/GooFit/Minuit2. If you download it to the current directory and use `add_subdirectory(Minuit2)`, the Minuit2 target will be available. Or, of course, you can make install and then `find_package(Minuit2)` will pick up the exported Minuit2 targets. (Not what I usually do, but someone contributed that, so I hope it works). Downloading it through CMake is possible too.

**Comment by AAAlvesJr** [comment]
It seems a good idea for the future.

**Comment by AAAlvesJr** [comment]
I deleted your comment. Looks more like an advertisement, so please send to the users forum.

**Comment by AAAlvesJr** [comment]
Soved addding guards to CMakeLists.txt.
