### ISSUE TITLE
Mismatch for LogLikelihood

### ISSUE THREAD

**Issue by henryiii** [MultithreadCorner/Hydra#5]
Line 132 of `LogLikelihoodFCN` tries to call `detail::LogLikelihood` with 8 arguments, but it really only takes 7. The second argument seems to be the culprit.

**Comment by AAAlvesJr** [comment]
Please, be more specific. Post your code  so I can see what are you tying to do.

**Comment by henryiii** [comment]
`hydra/LogLikelihood.h`

```cpp
        final=thrust::transform_reduce(select_system(system), first, last,
                detail::LogLikelihood<U, IteratorData, IteratorCache>(fFunctor, fFunctor.GetNorm(),
                        this->GetSumW()     , this->GetSumW2() ,
                        this->GetDataBegin(), this->GetCacheBegin(),
                        this->isWeighted()  , this->isCached()),
                        init, thrust::plus<GReal_t>());
```

Cannot call

`hydra/detail/functors/LogLikelihood.h`

```cpp
    LogLikelihood(FUNCTOR const& functor, GReal_t sumW, GReal_t sumW2, IteratorData dbegin, IteratorCache cbegin,
        GBool_t weighted, GBool_t cached):
```

Since the first one has 8 arguments and the second one has 7.

My code is at https://github.com/henryiii/HydraExamples/tree/master/src/novo_fit

**Comment by AAAlvesJr** [comment]
Ok... whatever, I got it and will  correct asap. It is a ugly  typo . Thanks.
A.A.

**Comment by AAAlvesJr** [comment]
fixed in the incoming release... under testing.
