### ISSUE TITLE
cmake building in OSX

### ISSUE THREAD

**Issue by AAAlvesJr** [MultithreadCorner/Hydra#53]
From hydra-users mailing list: 

 https://groups.google.com/d/msg/hydra-library-users/w6daxvrSzm0/4B4nmhcBAgAJ

Test if exchanging 

```
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
```
by
```
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
```
hurts the building in officially supported platforms.

**Comment by henryiii** [comment]
I've used it before in several systems, and it's recommended in other places, like in the [CMake cookbook](https://books.google.fr/books?id=x8JwDwAAQBAJ&pg=PA56&lpg=PA56&dq=CMAKE_CXX_COMPILER_ID%7D%22+MATCHES+%22Clang&source=bl&ots=d211ThpvL5&sig=ID9rahQj6J-V5w3ErI_OsJRbcBM&hl=en&sa=X&ved=2ahUKEwiJ5ZXPrtveAhWQy4UKHdclCIoQ6AEwCXoECAMQAQ#v=onepage&q=CMAKE_CXX_COMPILER_ID%7D%22%20MATCHES%20%22Clang&f=false).
