### ISSUE TITLE
Eigen need update

### ISSUE THREAD

**Issue by acontu** [MultithreadCorner/Hydra#56]
Current version produces the following warning when compiled using cuda 10:
/usr/local/cuda/include/host_defines.h:54:2: warning: #warning "host_defines.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "host_defines.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead."

**Comment by AAAlvesJr** [comment]
indeed, update of Eigen will be done in cuda 11 release.

**Comment by AAAlvesJr** [comment]
solved
