### ISSUE TITLE
fcn error when using hydra::JohnsonSUShape

### ISSUE THREAD

**Issue by dbrundu** [MultithreadCorner/Hydra#61]
Defining a hydra::JohnsonSUShape<> functor and using it in a make_loglikehood to perform a fit, like this:
`fcn   = hydra::make_loglikehood_fcn(model, dataset.begin(), dataset.end() );`
the following error appears:

```
Hydra-dev/Hydra-master/hydra/detail/LogLikelihoodFCN2.inl:111:60: error: no matching function for call to ‘log(hydra::GReal_t)’
     ( this->GetPDF().GetCoefSum() - this->GetDataSize()*log(this->GetPDF().GetCoefSum() ) ) - final;
```

**Comment by AAAlvesJr** [comment]
the overload hydra::log(hydra::complex) is found before than ::log(double) in the enclosing scope/namespace... but this does match and you get the error. Some few files still have this silly bug. It seems you found one of them. Thanks for posting, correcting now in master... await a few minutes, pull the repository and try again.
