### ISSUE TITLE
Step behaviour in hydra spline

### ISSUE THREAD

**Issue by dbrundu** [MultithreadCorner/Hydra#64]
Using the hydra spline to interpolate a simple set of data points `(x_i, y_i)` shows a drastic step behviour just after the data points themselves.
 At the exact values `x_i` the spline is evaluated correctly to `y_i`.
In the plot attached the data points are shown in blue, and the spline in green. In this case the spline is evaluated on the high granularity x scale.

![image](https://user-images.githubusercontent.com/24250316/52353067-1d4da200-2a2e-11e9-9b84-fcbf9594a065.png)

**Comment by AAAlvesJr** [comment]
Ugly! Just corrected that. Thanks 

https://github.com/MultithreadCorner/Hydra/commit/b58ec39b584aef59b51f7bd451c2ad7a0b54427a

**Comment by AAAlvesJr** [comment]
really solved now
https://github.com/MultithreadCorner/Hydra/commit/a7164a36c3af161498d8cb0120db05f472ca54bf
