### ISSUE TITLE
Using apply_filter for hydra::Decays

### ISSUE THREAD

**Issue by dbrundu** [MultithreadCorner/Hydra#66]
The hydra::apply_filter() has problems when applied to hydra::Decays containers. This seems related to type conversion and the interface of the lambda wrapper.
Please find attached a ROOT macro that emulates this issue (run it inside ROOT changing the file extension to .C or similiar).

[apply_filter_issue.txt](https://github.com/MultithreadCorner/Hydra/files/3128022/apply_filter_issue.txt)

**Comment by AAAlvesJr** [comment]
This issue is solved :

```
void apply_filter_issue()
{
  hydra::Decays<4, hydra::host::sys_t> Events(100);

  auto filter =  hydra::wrap_lambda( [=] __hydra_dual__ ( typename hydra::Decays<4, hydra::host::sys_t>::value_type& p ){
       return true;
  });
  auto Events_fltr = hydra::apply_filter(Events, filter);

}
```

runs now. please test.

**Comment by dbrundu** [comment]
This solves the problem.
