### ISSUE TITLE
restrict keyword

### ISSUE THREAD

**Issue by henryiii** [MultithreadCorner/Hydra#8]
The * before the `__restrict__` causes clang to report an error. GCC is happy with it before or after the `__restrict__`. Currently both cases are in Hydra. This issue requests a new symbol defined to take care of the different cases.

(Note: I believe the c++ `restrict` keyword might have a different syntax than `__restrict__`, does that version work?)

**Comment by AAAlvesJr** [comment]
The restrict keyword is a C99 thing. See here http://cellperformance.beyond3d.com/articles/2006/05/demystifying-the-restrict-keyword.html
In c++ compilers support this feature, with different syntax, as a special feature.
I will implement a specific symbol to take care of all compilers idiosyncrasies. Thanks

**Comment by AAAlvesJr** [comment]
Corrected. Actually we realized all compilers have consistent syntax here and the problem was caused by typos in some headers. Thanks.
