### ISSUE TITLE
Small bug in ProcessSplot - wrong initialization

### ISSUE THREAD

**Issue by dbrundu** [MultithreadCorner/Hydra#88]
The following line is a wrong initialization of the denominator variable (should be 0 instead of 1), causing the sum of sweights for each event to be systematically smaller than 1, and the associated global yields lower than those fitted.
Using 0 as initial value the inconsistency disappears.

https://github.com/MultithreadCorner/Hydra/blob/78fec1dc9aff8845cdc2732dfbafa39a61668564/hydra/detail/functors/ProcessSPlot.h#L206

**Comment by AAAlvesJr** [comment]
Sure !  Thank you!
