### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by henryiii** [MultithreadCorner/Hydra#9]
There is a missing include in `hydra/experimental/detail/Events.inl`:

```
#include <thrust/count.h>
```

For some reason, this only breaks the CPP backend (GCC on Goofy tested). Not sure why the other backends include count some way, but not cpp.

**Comment by henryiii** [comment]
This `#include <thrust/count.h>` is also missing in `hydra/PhaseSpace.h` and `hydra/Events.h` in Hydra dev. `#include <thrust/extrema.h>` (for `max_element`) is also missing in `hydra/Events.h`.

**Comment by AAAlvesJr** [comment]
Provides more detail about this. I observe no issue with that on my side.

**Comment by henryiii** [comment]
Try to compile with CPP backend (great for debugging). The use of `thrust::count` needs `#include <thrust/count.h>` and `thrust::max_element` needs `#include <thrust/extrema.h>`.

In general it's good to directly include the header of something you are using, anyway.

**Comment by AAAlvesJr** [comment]
it is usualy what is done... does not cost anything to me implement that in the incoming release.
