### ISSUE TITLE
Wrong sign in the denominator of BreitWignerLineShape

### ISSUE THREAD

**Issue by dbrundu** [MultithreadCorner/Hydra#90]
Wrong sign in the real part of the denominator of the BreitWignerLineShape functor.
https://github.com/MultithreadCorner/Hydra/blob/1719ae17a20409976deef64995efad76999ca908/hydra/functions/BreitWignerLineShape.h#L247
This should be :
`resonance_mass*resonance_mass - m*m`

**Comment by AAAlvesJr** [comment]
Solved!
