### ISSUE TITLE
Missing include in ZemachFunctions

### ISSUE THREAD

**Issue by dbrundu** [MultithreadCorner/Hydra#91]
The type `hydra::Wave`, that appears in the template of  the ZemachFunctions functor, could cause an error, since its declaration is in hydra/functions/Utils.h header file, that is missing.

https://github.com/MultithreadCorner/Hydra/blob/1719ae17a20409976deef64995efad76999ca908/hydra/functions/ZemachFunctions.h#L63

**Comment by AAAlvesJr** [comment]
solved!
