### ISSUE TITLE
Fail of hydra::unweight( dataset , functor)

### ISSUE THREAD

**Issue by dbrundu** [MultithreadCorner/Hydra#95]
The following simple example, in which I'm calling the function` hydra::unweight( dataset , functor)`,  produces a compile time error:

```
    declarg(xvar,  double)
    declarg(yvar,  double)

    int main(int argv, char** argc)
    {
       hydra::multivector<hydra::tuple<xvar, yvar> , hydra::host::sys_t> dataset;

        for(size_t i=0; i<100; i++ ) dataset.push_back( hydra::tuple<xvar, yvar>(i, i) );
    
        auto functor  = hydra::wrap_lambda(
            [] __hydra_dual__ (xvar x, yvar y) { return  ::sqrt(x*y); } );
   
        auto dataset_unwgt = hydra::unweight( dataset, functor);

        return 0;
    }
```
The error remains if the multivector is instantiated in the device.

**Comment by dbrundu** [comment]
Here you can find the complete error.

[error_log.log](https://github.com/MultithreadCorner/Hydra/files/4844937/error_log.log)

**Comment by AAAlvesJr** [comment]
I pushed a possible solution some days ago. Please, could you test it?
Let me know if runs fine... so we can close this issue as well. 
Cheers

**Comment by dbrundu** [comment]
Tested, it runs perfectly.

**Comment by AAAlvesJr** [comment]
Thanks... closing
