### ISSUE TITLE
Grammar fix

### ISSUE THREAD

**Issue by adicanto** [MultithreadCorner/Hydra#98]
https://github.com/MultithreadCorner/Hydra/blob/d87b68ae7632fd11b19c5a5dfd581bbc624d1b80/examples/phys/breit_wigner_plus_chebychev.inl#L228

Coeficient -> Coefficient

**Comment by adicanto** [comment]
Suggest to run  https://github.com/codespell-project/codespell to look for more misspelled words

**Comment by AAAlvesJr** [comment]
Should be fixed... please check and let me know.
Thank you very much.

**Comment by AAAlvesJr** [comment]
I am marking this issue as solved. If you find further problems, please let us know. Cheers.
